# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-26 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='total_like',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
